- .github/workflows/linting.yml
- .github/workflows/regression.yml
- rename job for coherence
- checkout submodules using actions
- fix yaml block
TEST=https://github.com/proppy/globalfoundries-pdk-libs-gf180mcu_fd_pv/actions
> improve workflows

- .github/workflows/regression.yml
> Updating actions to run drc regression

- .github/workflows/linting.yml
- .rubocop.yml
- Makefile
- klayout/drc/rule_decks/drc_bjt.drc
- klayout/drc/rule_decks/dualgate.drc
- klayout/drc/rule_decks/dummy_exclude.drc
- klayout/drc/rule_decks/efuse.drc
- klayout/drc/rule_decks/hres.drc
- klayout/drc/rule_decks/lres.drc
- klayout/drc/rule_decks/lvs_bjt.drc
- klayout/drc/rule_decks/main.drc
- klayout/drc/rule_decks/mcell.drc
- klayout/drc/rule_decks/otp_mk.drc
- klayout/drc/rule_decks/pres.drc
- klayout/drc/rule_decks/tail.drc
- klayout/drc/testing/run_regression.py
Fixes #32 
- Adding ruby linting checks for git actions
- Cleaning all added ruby files.
> Adding linting checks and cleaning all files

- .github/workflows/linting.yml
- .github/workflows/regression.yml
- Makefile
- klayout/drc/rule_decks/main.drc
- klayout/drc/rule_decks/tail.drc
> Fixing some linting issues for ruby files

- klayout/drc/rule_decks/dummy_exclude.drc
> Fixing and cleaning some rules in dummy_exclude table

- klayout/drc/rule_decks/lvs_bjt.drc
> Optimizing rules in LVS_BJT table

- klayout/drc/rule_decks/drc_bjt.drc
> Optimizing rules in DRC_BJT table

- klayout/drc/rule_decks/mcell.drc
> Removing over processing derivations for MCELL

- klayout/drc/rule_decks/comp.drc
> Adding link to NOT DRC rules for COMP

- klayout/drc/rule_decks/nwell.drc
> Cleaning nwell table for GF180MCU DRC

- .github/workflows/drc_regression.yml
- Makefile
> Renaming DRC git workflow

- klayout/drc/rule_decks/metaltop.drc
> Adding METALTOP 11k support for GF180MCU DRC

- klayout/drc/rule_decks/main.drc
- klayout/drc/run_drc.py
- klayout/drc/testing/README.md
- klayout/drc/testing/run_regression.py
- Updating main runset with new connectivity functions
- Fixing linting issues for these functions
- Updating klayout version check to be matched with the connectivity change
> Updating main runset with new connectivity functions

- klayout/drc/testing/run_regression.py
> Updating regression to fix some issues

- klayout/drc/README.md
- klayout/drc/testing/README.md
- klayout/drc/testing/testcases/README.md
> Updating testing docs for GF180MCU DRC

- klayout/drc/rule_decks/poly2.drc
- klayout/lvs/README.md
Fixes https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/107
> Fixing PL.3_LV DRC rule for GF180MCU

- klayout/lvs/rule_decks/bjt_connections.lvs
- klayout/lvs/rule_decks/devices_connections.lvs
- klayout/lvs/rule_decks/diode_connections.lvs
- klayout/lvs/rule_decks/efuse_connections.lvs
- klayout/lvs/rule_decks/general_connections.lvs
- klayout/lvs/rule_decks/general_derivations.lvs
- klayout/lvs/rule_decks/layers_definitions.lvs
- klayout/lvs/rule_decks/mimcap_connections.lvs
- klayout/lvs/rule_decks/mimcap_derivations.lvs
- klayout/lvs/rule_decks/mos_connections.lvs
- klayout/lvs/rule_decks/res_connections.lvs
- klayout/lvs/rule_decks/res_extraction.lvs
> Splitting devices connections, Adjusting connectivity and metal stack def for GF180MCU LVS

- klayout/lvs/run_lvs.py
- klayout/lvs/testing/run_regression.py
> Updating run lvs script for GF180MCU

- Makefile
> Adding lvs swich checking in git actions for GF180MCU

- klayout/lvs/README.md
- klayout/lvs/gf180mcu.lvs
- klayout/lvs/run_lvs.py
- klayout/lvs/testing/testcases/README.md
> Minor updates for GF180MCU LVS

- klayout/lvs/rule_decks/custom_classes.lvs
> Updating LVS to be compatible with latest klayout

- klayout/lvs/rule_decks/res_derivations.lvs
- klayout/lvs/rule_decks/res_extraction.lvs
- klayout/lvs/run_lvs.py
Fixes #<issue_number_goes_here>
> modify res lvs and adding variant D with 6LM to run_lvs

- klayout/drc/rule_decks/main.drc
- klayout/drc/run_drc.py
Fixes #<issue_number_goes_here>
> updating run_drc.py to match new macros and fix main.drc syntax error

- klayout/lvs/rule_decks/mimcap_extraction.lvs
> Cleaning mimcap LVS rule deck

- klayout/lvs/gf180mcu.lvs
- klayout/lvs/rule_decks/layers_definitions.lvs
> Updating lvs for gf180mcu

- klayout/drc/rule_decks/dnwell.drc
- klayout/drc/rule_decks/dnwell_split.drc
- klayout/drc/rule_decks/ldnmos.drc
- klayout/drc/rule_decks/ldnmos_split.drc
- klayout/drc/rule_decks/ldpmos.drc
- klayout/drc/rule_decks/ldpmos_split.drc
- klayout/drc/rule_decks/lvpwell.drc
- klayout/drc/rule_decks/lvpwell_split.drc
- klayout/drc/rule_decks/main.drc
- klayout/drc/rule_decks/nat.drc
- klayout/drc/rule_decks/nat_split.drc
- klayout/drc/rule_decks/nwell.drc
- klayout/drc/rule_decks/nwell_split.drc
> More DRC optimization for GF180MCU

- klayout/drc/rule_decks/antenna.drc
- klayout/drc/rule_decks/density.drc
- klayout/drc/rule_decks/layers_def.drc
- klayout/drc/run_drc.py
> Removing dummy exclusion for some layers
